#! /usr/bin/env ruby
require "pg"

CONNECTION = PG.connect(dbname: "expenses")

class ExpenseData
  def initialize
    @connection = PG.connect(dbname: "expenses")
  end

  def format_row(tuple)
    features = [ tuple["id"],
                 tuple["created_on"],
                 tuple["amount"].rjust(12),
                 tuple["memo"] ]
  
    puts features.join(" | ")
  end

  def display_expenses(expenses)
    expenses.each do |tuple|
      format_row(tuple)
    end
  end
  
  def list_expenses
    result = @connection.exec("SELECT * FROM expenses ORDER BY created_on ASC;")
    display_expenses(result)
  end

  def add_expense(amount, memo)
    sql = "INSERT INTO expenses (amount, memo) VALUES ($1, $2);"
    @connection.exec_params(sql, [amount, memo]) 
  end

  def search_expenses(term)
    sql = "SELECT * FROM expenses WHERE memo ILIKE $1"
    result = @connection.exec_params(sql, ["%#{term}%"])
    display_expenses(result)
  end
end

class CLI
  def initialize
    @application = ExpenseData.new
  end

  def run(args)
    input_command, *input_args = args
  
    case input_command
    when nil
      display_help
    when "list"
      @application.list_expenses
    when "add"
      amount = input_args[0]
      memo   = input_args[1]
      abort "You must provide an amount and memo." unless amount && memo
    
      @application.add_expense(amount, memo)
    when "search"
      term = input_args[0]
      abort "You must provide a search term." unless term

      @application.search_expenses(term)
    end
  end

  def display_help
    puts <<~HELP
      An expense recording system
  
      Commands:
  
      add AMOUNT MEMO [DATE] - record a new expense
      clear - delete all expenses
      list - list all expenses
      delete NUMBER - remove expense with id NUMBER
      search QUERY - list expenses with a matching memo field
    HELP
  end
end

CLI.new.run(ARGV)